@Library('common-shared-lib') _

pipeline {
    agent any

    environment {
        IMAGE = "docker.io/vanukurilikhita/${env.JOB_NAME}:latest"
    }

    stages {
        stage("Checkout") {
            steps { checkout scm }
        }

        stage("Build") {
            steps { buildApp() }
        }

        stage("Test") {
            steps { testApp() }
        }

        stage("Docker Build") {
            steps { dockerBuild IMAGE }
        }

        stage("Deploy") {
            steps { deployApp("${env.JOB_NAME}") }
        }
    }
}

